name: 'Turbo GoReleaser'
description: 'Multi-component release automation for TurboRepo with GoReleaser Pro'
author: 'jameswlane'

branding:
  icon: 'package'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API operations'
    required: true
  
  goreleaser-key:
    description: 'GoReleaser Pro license key'
    required: false
  
  goreleaser-version:
    description: 'GoReleaser version to use'
    required: false
    default: '~> v2'
  
  turbo-token:
    description: 'Turbo remote cache token'
    required: false
  
  turbo-team:
    description: 'Turbo team identifier'
    required: false
  
  release-type:
    description: 'Components to release: all, apps, packages'
    required: false
    default: 'all'
  
  tag-format:
    description: 'Tag format: npm (@scope/name@v1.0.0), slash (name/v1.0.0), or standard (v1.0.0)'
    required: false
    default: 'slash'
  
  dry-run:
    description: 'Run without creating actual releases'
    required: false
    default: 'false'
  
  conventional-commits:
    description: 'Use conventional commits for versioning'
    required: false
    default: 'true'
  
  working-directory:
    description: 'Working directory for the action'
    required: false
    default: '.'

outputs:
  released-packages:
    description: 'JSON array of released packages with their versions'
  
  release-notes:
    description: 'Aggregated release notes for all packages'
  
  tags-created:
    description: 'List of Git tags created during the release'
  
  goreleaser-artifacts:
    description: 'JSON metadata of GoReleaser build artifacts'

runs:
  using: 'composite'
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        install: true
        cache: true
        install_args: "node pnpm go"

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: ${{ inputs.goreleaser-key && 'goreleaser-pro' || 'goreleaser' }}
        version: ${{ inputs.goreleaser-version }}
        install-only: true

    - name: Run Turbo GoReleaser
      shell: bash
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_GORELEASER-KEY: ${{ inputs.goreleaser-key }}
        INPUT_GORELEASER-VERSION: ${{ inputs.goreleaser-version }}
        INPUT_TURBO-TOKEN: ${{ inputs.turbo-token }}
        INPUT_TURBO-TEAM: ${{ inputs.turbo-team }}
        INPUT_RELEASE-TYPE: ${{ inputs.release-type }}
        INPUT_TAG-FORMAT: ${{ inputs.tag-format }}
        INPUT_DRY-RUN: ${{ inputs.dry-run }}
        INPUT_CONVENTIONAL-COMMITS: ${{ inputs.conventional-commits }}
        INPUT_WORKING-DIRECTORY: ${{ inputs.working-directory }}
      run: |
        cd ${{ github.action_path }}
        node dist/index.js