name: 'Turbo GoReleaser'
description: 'Multi-component release automation for TurboRepo with GoReleaser Pro'
author: 'jameswlane'

branding:
  icon: 'package'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for API operations'
    required: true
    default: ${{ github.token }}
  
  goreleaser-key:
    description: 'GoReleaser Pro license key'
    required: false
  
  goreleaser-version:
    description: 'GoReleaser version to use'
    required: false
    default: '~> v2'
  
  turbo-token:
    description: 'Turbo remote cache token'
    required: false
  
  turbo-team:
    description: 'Turbo team identifier'
    required: false
  
  release-type:
    description: 'Components to release: all, apps, packages'
    required: false
    default: 'all'
  
  tag-format:
    description: 'Tag format: npm (@scope/name@v1.0.0), slash (name/v1.0.0), or standard (v1.0.0)'
    required: false
    default: 'slash'
  
  dry-run:
    description: 'Run without creating actual releases'
    required: false
    default: 'false'
  
  conventional-commits:
    description: 'Use conventional commits for versioning'
    required: false
    default: 'true'
  
  working-directory:
    description: 'Working directory for the action'
    required: false
    default: '.'

outputs:
  released-packages:
    description: 'JSON array of released packages with their versions'
  
  release-notes:
    description: 'Aggregated release notes for all packages'
  
  tags-created:
    description: 'List of Git tags created during the release'
  
  goreleaser-artifacts:
    description: 'JSON metadata of GoReleaser build artifacts'

runs:
  using: 'node20'
  main: 'dist/index.js'