name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for change detection

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Turbo
        run: npm install -g turbo

      - name: Run Turbo GoReleaser
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          goreleaser-key: ${{ secrets.GORELEASER_KEY }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-team: ${{ vars.TURBO_TEAM }}
          release-type: all
          tag-format: slash
          conventional-commits: 'true'