name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for change detection

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Setup Turbo
        run: pnpm add -g turbo

      - name: Run Turbo GoReleaser
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          goreleaser-key: ${{ secrets.GORELEASER_KEY }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-team: ${{ vars.TURBO_TEAM }}
          release-type: all
          tag-format: slash
          conventional-commits: 'true'