name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test:run

      - name: Build and Package
        run: |
          pnpm run build
          pnpm run package

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          semantic_version: 24
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # After a successful release, update the major version tag with dist files
      - name: Update Major Version Tag
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          # Extract major version from the new version
          VERSION="${{ steps.semantic.outputs.new_release_version }}"
          MAJOR_VERSION="v${VERSION%%.*}"

          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create or checkout the release branch for the major version
          git checkout -B "release/${MAJOR_VERSION}"

          # Add dist files (removing from gitignore temporarily)
          sed -i '/^dist\//d' .gitignore
          sed -i '/\*\/dist\//d' .gitignore
          git add dist/
          git commit -m "build: add dist files for ${MAJOR_VERSION}" || echo "No dist changes"

          # Force update the major version tag to this commit
          git tag -f "${MAJOR_VERSION}"

          # Push the tag
          git push origin "${MAJOR_VERSION}" --force