name: Update Distribution Files

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to update (e.g., v1, v1.2.3)'
        required: true
        default: 'v1'

permissions:
  contents: write

jobs:
  update-dist:
    name: Update dist files for release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Build and Package
        run: |
          pnpm run build
          pnpm run package

      - name: Update Tag with dist files
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create a temporary branch
          TEMP_BRANCH="update-dist-${{ github.event.inputs.version }}-$(date +%s)"
          git checkout -b "${TEMP_BRANCH}"

          # Remove dist from gitignore temporarily and add dist files
          sed -i '/^dist\//d' .gitignore
          sed -i '/\*\/dist\//d' .gitignore
          git add dist/

          # Commit if there are changes
          if git diff --cached --quiet; then
            echo "No dist changes to commit"
          else
            git commit -m "build: add dist files for ${{ github.event.inputs.version }}"
          fi

          # Force update the tag to point to this commit
          git tag -f "${{ github.event.inputs.version }}"

          # Push the updated tag
          git push origin "${{ github.event.inputs.version }}" --force

          echo "✅ Successfully updated ${{ github.event.inputs.version }} with dist files"